# Generated by Django 4.2.11 on 2024-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[(0, 'masculino'), (1, 'femenino'), (2, 'no responde')], max_length=100)),
            ],
        ),
    ]
