# Generated by Django 4.2.11 on 2024-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customfields_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfields',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customfields',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Prefers not to say')]),
        ),
    ]
